sonar.projectKey=taskflow
sonar.projectName=TaskFlow
sonar.projectVersion=1.0
sonar.sources=backend
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts
sonar.sourceEncoding=UTF-8
sonar.host.url=http://host.docker.internal:9000
sonar.token=sqp_0e60e6c3c178dde8e7c78d53cc38c7422bea05aa