sonar.projectKey=TaskFlow
sonar.projectName=TaskFlow
sonar.projectVersion=1.0
sonar.sources=backend
sonar.exclusions=**/node_modules/**,**/dist/**,**/dist/*,**/*.js,**/coverage/**,**/.git/**,**/test/**,**/*.json,**/*.md
sonar.inclusions=**/*.ts
sonar.sourceEncoding=UTF-8
sonar.host.url=http://host.docker.internal:9000
sonar.token=sqa_e9c8a1ead4c7b53a3cd9ad09d443a701989eacd5