import { Injectable, computed, inject, signal } from '@angular/core';

export type AppLanguage = 'en' | 'ar';

const STORAGE_KEY = 'taskflow-language';

const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  en: {
    'common.loading': 'Loading',
    'common.please-wait': 'Please wait while the action is processed.',
    'common.menu': 'Menu',
    'common.settings': 'Settings',
    'common.logout': 'Logout',
    'common.light': 'Light',
    'common.dark': 'Dark',
    'common.login': 'Login',
    'common.register': 'Register',
    'common.back': 'Back',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.remember-me': 'Remember me',
    'common.forgot-password': 'Forgot password?',
    'common.sign-in': 'Sign in',
    'common.verifying': 'Verifying...',
    'common.verify': 'Verify',
    'common.welcome': 'Welcome',
    'common.create-account': 'Create your account',
    'common.company-name': 'Company name',
    'common.first-name': 'First name',
    'common.last-name': 'Last name',
    'common.optional': 'Optional',
    'common.terms': 'I accept the Terms of Use',
    'common.submit': 'Submit',
    'common.dashboard': 'Dashboard',
    'common.home': 'Home',
    'common.clients': 'Clients',
    'common.expenses': 'Expenses',
    'common.invoices': 'Invoices',
    'common.team': 'Team',
    'common.ai-lab': 'AI Lab',
    'common.ai-risk': 'Invoice Risk',
    'common.pricing': 'Pricing',
    'common.features': 'Features',
    'common.how-it-works': 'How it works',
    'common.why-taskflow': 'Why TaskFlow?',
    'common.free-trial': 'Free 30-day trial — No credit card required',
    'common.start-now': 'Start now',
    'common.get-started': 'Get started',
    'common.see-pricing': 'See pricing',
    'common.support': 'Support',
    'common.for-business': 'For businesses',
    'common.accountants': 'Accountants',
    'common.account': 'Account',
    'common.all': 'All',
    'common.admin': 'Admin',
    'common.me': 'Me',
    'common.error': 'Error',
    'common.unknown-error': 'Unknown error',
    'common.status.pending': 'Pending',
    'common.status.approved': 'Approved',
    'common.status.rejected': 'Rejected',
    'common.status.blocked': 'Blocked',
    'common.status.active': 'Active',
    'common.status.completed': 'Completed',
    'common.current-language': 'Language',
    'common.language-en': 'EN',
    'common.language-ar': 'AR',
    'common.show-password': 'Show password',
    'common.hide-password': 'Hide password',
    'common.toggle-theme': 'Toggle theme',
    'common.enter-email': 'Enter your email to start recovery.',
    'common.choose-method': 'Choose a method',
    'common.security-questions': 'Security questions',
    'common.link-by-email': 'Reset link by email',
    'common.contact-admin': 'Contact the administrator',
    'common.new-password': 'New password',
    'common.confirm-password': 'Confirm password',
    'auth.login-to-space': 'Sign in to access your workspace.',
    'auth.email-placeholder': 'e.g. name@company.com',
    'auth.password-placeholder': 'Your password',
    'auth.no-account': 'No account yet?',
    'auth.twofa-title': '2FA verification',
    'auth.twofa-description': 'Enter the 6-digit code from your authenticator app.',
    'auth.verification-code': 'Verification code',
    'auth.create-account-desc': 'Free 30-day trial, no card required 🎉',
    'auth.company-category': 'Company category (optional)',
    'auth.company-category-select': 'Select a category',
    'auth.category-retail': 'Retail',
    'auth.category-services': 'Services',
    'register.back-to-login': 'Back to login',
    'register.sent': 'Registration sent',
    'register.first-name-placeholder': 'Your first name',
    'register.last-name-placeholder': 'Your last name',
    'register.continue-with': 'or continue with',
    'auth.category-technology': 'Technology',
    'auth.category-restaurant': 'Restaurant',
    'auth.category-freelance': 'Freelance',
    'auth.category-healthcare': 'Healthcare',
    'auth.category-education': 'Education',
    'auth.category-other': 'Other',
    'auth.company-placeholder': 'Company name',
    'auth.professional-email': 'Professional email',
    'auth.accept-terms': 'I accept the Terms of Use',
    'auth.already-account': 'Already have an account?',
    'auth.social-google': 'Continue with Google',
    'auth.social-facebook': 'Continue with Facebook',
    'auth.social-linkedin': 'Continue with LinkedIn',
    'auth.social-apple': 'Continue with Apple',
    'auth.otp-invalid': 'Invalid OTP code',
    'auth.secure-access': 'Secure Access',
    'auth.google-error': 'Error during Google connection.',
    'auth.google-loading': 'Google Sign-In is not yet loaded. Please try again.',
    'auth.validation.required': '{field} is required.',
    'auth.validation.minlength': '{field} must contain at least {count} characters.',
    'auth.blocked-temporarily': 'Account temporarily blocked.',
    'auth.pending-approval': 'Your account is waiting for administrator approval.',
    'auth.invalid-credentials': 'Incorrect email address or password.',
    'auth.invalid-password': 'Incorrect password.',
    'auth.email-required': 'Professional email is required.',
    'auth.invalid-email': 'Please enter a valid email address.',
    'auth.accept-required': 'You must accept the Terms of Use.',
    'auth.email-already-used': 'An account with this email already exists.',
    'auth.register-success-message': 'Your registration request has been sent successfully.\nPlease wait, you will soon receive an email from the Super Admin\ncontaining your email and password to sign in.',
    'home.hero-line1': 'Smart management.',
    'home.hero-line2': 'Local. Secure.',
    'home.hero-line3': 'Tunisian.',
    'home.hero-description': 'Manage your invoices, expenses and teams in one platform — with full data sovereignty in Tunisia.',
    'forgot.title': 'Forgot password',
    'forgot.description': 'Enter your email to start recovery.',
    'forgot.step-choose': 'Choose a method',
    'forgot.step-choose-desc': 'How would you like to reset your password?',
    'forgot.security-question': 'Security questions',
    'forgot.security-question-desc': 'Answer the configured questions.',
    'forgot.email-link': 'Reset link by email',
    'forgot.email-link-desc': 'Receive a password reset link.',
    'forgot.contact-admin': 'Contact the administrator',
    'forgot.contact-admin-desc': 'Ask the Super Admin for help.',
    'forgot.contact-admin-error': 'An error occurred while contacting the administrator.',
    'forgot.invalid-email': 'Please enter a valid email address.',
    'forgot.email-not-found': 'Email not found.',
    'forgot.email-sent-title': 'Email sent',
    'forgot.email-sent-message': 'A reset link has been sent to your email address.',
    'forgot.request-sent-title': 'Request sent',
    'forgot.request-sent-message': 'Your request has been sent to the Super Admin. You will receive a notification soon.',
    'forgot.answers-incorrect': 'One or more answers are incorrect.',
    'forgot.reset-error': 'Error while resetting the password.',
    'forgot.new-password-title': 'New password',
    'forgot.new-password-desc': 'Create a new secure password.',
    'forgot.success': 'Success!',
    'forgot.reset-success': 'Password reset successfully.',
    'forgot.login-now': 'Sign in now',
    'forgot.loading': 'Loading...',
    'forgot.continue': 'Continue',
    'forgot.verify': 'Verify',
    'forgot.verifying': 'Verifying...',
    'forgot.answer': 'Your answer',
    'forgot.password-strength': 'Strength',
    'forgot.min-eight': '8 characters minimum',
    'forgot.uppercase': 'One uppercase letter',
    'forgot.lowercase': 'One lowercase letter',
    'forgot.number': 'One number',
    'forgot.special': 'One special character',
    'forgot.match': 'Passwords match',
    'forgot.resetting': 'Resetting...',
    'forgot.redirection-countdown': 'Redirecting to login page in {count} seconds...',
    'reset.missing-token': 'Reset token is missing.',
    'reset.success': 'Password reset successfully. Redirecting...',
    'change.title': 'Change your password',
    'change.description': 'For your security, please set a new password.',
    'change.temporary': 'You are using a temporary password. Please change it now.',
    'change.current': 'Current password',
    'change.new': 'New password',
    'change.confirm': 'Confirm password',
    'change.strength': 'Strength',
    'change.strength-weak': 'Weak',
    'change.strength-medium': 'Medium',
    'change.strength-strong': 'Strong',
    'change.change-now': 'Change now',
    'change.please-change': 'Please change it now.',
    'change.requirements': 'Requirements',
    'change.special': 'One special character',
    'change.success': 'Password updated successfully. Redirecting...',
    'change.error': 'Unknown error',
    'onboarding.company-info': 'Company Info',
    'onboarding.your-business': 'Your Business',
    'onboarding.complete-profile': 'Complete Your Company Profile',
    'onboarding.profile-desc': 'This info will appear on your invoices. Takes 1 minute.',
    'onboarding.company-name': 'Company Name',
    'onboarding.set-during-reg': 'Set during registration',
    'onboarding.address': 'Address',
    'onboarding.address-placeholder': '123 Main Street, City...',
    'onboarding.country': 'Country',
    'onboarding.phone': 'Phone',
    'onboarding.logo-url': 'Logo URL',
    'onboarding.logo-placeholder': 'https://yourlogo.com/logo.png',
    'onboarding.invalid-logo': 'Invalid image URL',
    'onboarding.required': 'This field is required',
    'onboarding.save-continue': 'Save & Continue',
    'onboarding.saving': 'Saving...',
    'onboarding.save-error': 'Failed to save. Please try again.',
    'onboarding.create-business-title': 'Create Your First Business',
    'onboarding.create-business-desc': 'You can add more businesses later from settings.',
    'onboarding.auto-country': 'Auto-selected based on your country',
    'onboarding.optional-later': 'Optional - you can add this later',
    'onboarding.review-business': 'Review Your Business',
    'onboarding.create-go-dashboard': 'Create Business & Go to Dashboard',
    'onboarding.creating': 'Creating...',
    'onboarding.create-error': 'Failed to create business. Please try again.',
    'security.title': 'Security Questions',
    'security.description': 'Use these details for account recovery.',
    'security.question': 'Question',
    'security.answer': 'Answer',
    'security.saved': 'Security questions saved.',
    'security.save': 'Save',
    'security.saving': 'Saving...',
    'security.error': 'Error while saving',
    'admin.load-registrations-error': 'Failed to load pending registrations.',
    'home.business-feed': 'Business Feed',
    'home.more-info': 'More info available',
    'home.insights': 'Insights',
    'home.tab-accounting': 'Accounting',
    'home.tab-sales': 'Sales & Get Paid',
    'home.tab-marketing': 'Marketing',
    'home.tab-expenses': 'Expenses & Bills',
    'home.tab-hub': 'Customer Hub',
    'home.customer-agent': 'Customer Agent',
    'home.accounting-agent': 'Accounting Agent',
    'home.expense-agent': 'Expense Agent',
    'home.client-agent': 'Customer Agent',
    'home.marketing-agent': 'Marketing Agent',
    'home.email-agent': 'Email Agent',
    'home.seo-agent': 'SEO Agent',
    'home.budget-agent': 'Budget Agent',
    'home.vat-agent': 'VAT Agent',
    'home.sales-agent': 'Sales Agent',
    'home.transactions-categorized': 'Transactions categorized',
    'home.sales-on-track': 'Sales are back on track',
    'home.new-leads-review': 'New leads ready for review',
    'home.bills-processed': 'Bills processed',
    'home.open-tickets': 'Open tickets',
    'home.processed-invoices': 'processed invoices',
    'home.tracked': 'tracked',
    'home.new-leads': 'new leads',
    'home.active-campaigns': 'active campaigns',
    'home.sent-emails': 'sent emails',
    'home.new-visitors': 'new visitors',
    'home.pending-invoices': 'pending invoices',
    'home.used-tnd': 'TND used',
    'home.vat-tnd': 'TND VAT',
    'home.transactions': 'transactions',
    'home.tracked-tnd': 'TND tracked',
    'home.lead': 'lead',
    'home.chequing-account': 'Chequing account',
    'home.mastercard': 'Mastercard',
    'home.create-account-step': 'Create an account',
    'home.create-account-desc': 'Sign up in a few seconds.',
    'home.setup-company-step': 'Set up your company',
    'home.setup-company-desc': 'Define your teams and settings.',
    'home.manage-step': 'Manage tasks & finances',
    'home.manage-step-desc': 'Track activity, invoices and expenses.',
    'common.step': 'Step',
    'home.revenue': 'Revenue',
    'home.expenses': 'Expenses',
    'home.profit': 'Profit',
    'home.active-projects': 'Active Projects',
    'home.leads': 'Leads',
    'home.bank-accounts': 'Bank Accounts',
    'home.cash-flow-expenses': 'Cash Flow & Expenses',
    'home.current-cash-balance': 'Current cash balance',
    'home.infrastructure': 'Infrastructure',
    'home.marketing': 'Marketing',
    'home.hr': 'HR',
    'home.other': 'Other',
    'home.data-in-tunisia': '🇹🇳 Data hosted in Tunisia',
    'home.compliance-guaranteed': 'Compliance guaranteed',
    'home.fast-onboarding': 'Quick onboarding, productive from day one.',
    'home.intuitive-ux': 'Intuitive UX',
    'home.multi-tenant-security': 'Strict tenant isolation, best practices.',
    'home.advanced-reports': 'KPIs, export, and custom views.',
    'home.your-data-stays': 'Your data stays in Tunisia. Period.',
    'home.tunisian-hosting': '100% Tunisian Hosting',
    'home.hosting-desc': 'OVH Tunisia servers, no transfer outside borders',
    'home.inpdp': 'INPDP Compliance',
    'home.inpdp-desc': 'Full respect of organic law no. 2004-63',
    'home.local-payment': 'Local Payment',
    'home.payment-desc': 'Integration with Tunisian banks and Sobflous',
    'home.our-team': 'Our Team',
    'home.try-free': 'Try TaskFlow for free',
    'home.subscribe': 'Subscribe',
    'home.tips': 'Receive our tips',
    'home.tips-desc': 'Receive our tips to better manage your business',
    'home.thanks': 'Thank you, you are subscribed!',
    'home.plan-free': 'Free',
    'home.plan-pro': 'Pro',
    'home.plan-enterprise': 'Enterprise',
    'home.price-free': '0 TND',
    'home.price-pro': '49 TND / month',
    'home.price-enterprise': 'Contact us',
    'home.sso': 'SSO',
    'home.advanced-integrations': 'Advanced integrations',
    'home.secure-user-friendly': 'Secure and user-friendly',
    'home.banking-made-hassle-free': 'Banking made hassle-free',
    'home.helpful-banking-support': 'Helpful banking support',
    'home.account-holder-since-2015': 'Account holder since 2015',
    'home.account-holder-since-2021': 'Account holder since 2021',
    'home.account-holder-since-2020': 'Account holder since 2020',
    'home.bank-interest': 'Bank interest',
    'home.crypto-currency': 'Crypto currency',
    'home.share-market': 'Share market',
    'home.contact': 'Contact',
    'home.faq': 'FAQ',
    'home.privacy': 'Privacy policy',
    'register.tunisian-hosted': '🇹🇳 Data hosted in Tunisia • INPDP compliance guaranteed',
    'settings.security-added': 'Security question added',
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Quick overview of your activity.',
    'dashboard.period': 'This month',
    'dashboard.revenue': 'Revenue',
    'dashboard.expenses': 'Expenses',
    'dashboard.profit': 'Profit',
    'dashboard.performance': 'Performance',
    'dashboard.shortcuts': 'Shortcuts',
    'dashboard.recent-invoices': 'Recent invoices',
    'dashboard.latest-activities': 'Latest activities',
    'dashboard.monthly-change': 'vs last month',
    'dashboard.margin': 'Margin',
    'dashboard.recent': 'Recent activity',
    'dashboard.col-client': 'Client',
    'dashboard.col-amount': 'Amount',
    'dashboard.col-status': 'Status',
    'dashboard.col-issued': 'Issued on',
    'ai.title': 'AI Expense Classifier',
    'ai.subtitle': 'Train and test the from-scratch model on expense descriptions.',
    'ai.input-label': 'Description to classify',
    'ai.input-placeholder': 'Example: monthly Google Workspace subscription for the sales team',
    'ai.predict': 'Classify',
    'ai.retrain': 'Retrain model',
    'ai.model-card': 'Model status',
    'ai.training-accuracy': 'Training accuracy',
    'ai.training-examples': 'Training examples',
    'ai.vocabulary': 'Vocabulary size',
    'ai.top-label': 'Best prediction',
    'ai.confidence': 'Confidence',
    'ai.matched-tokens': 'Matched tokens',
    'ai.no-result': 'No prediction yet. Enter a description and classify it.',
    'ai.load-error': 'Unable to load model information.',
    'ai-risk.title': 'Invoice Delay Risk Model',
    'ai-risk.subtitle': 'Estimate the risk that an invoice will be paid late using invoice and customer history features.',
    'ai-risk.client-context': 'Client context',
    'ai-risk.business': 'Business',
    'ai-risk.client': 'Client',
    'ai-risk.select-business': 'Select a business',
    'ai-risk.select-client': 'Select a client',
    'ai-risk.auto-fill-note': 'Select a client and the form will auto-fill from its invoice history.',
    'ai-risk.no-client-data': 'No client selected yet. Choose a business and a client to auto-fill the features.',
    'ai-risk.input-label': 'Invoice features',
    'ai-risk.amount': 'Amount',
    'ai-risk.due-days': 'Payment term (days)',
    'ai-risk.client-late-ratio': 'Client late ratio',
    'ai-risk.previous-late-count': 'Previous late invoices',
    'ai-risk.open-invoices': 'Open invoices',
    'ai-risk.total-invoices': 'Total invoices',
    'ai-risk.paid-invoices': 'Paid invoices',
    'ai-risk.late-invoices': 'Late paid invoices',
    'ai-risk.late-ratio': 'Late ratio',
    'ai-risk.latest-amount': 'Latest historical invoice amount',
    'ai-risk.predict': 'Estimate risk',
    'ai-risk.retrain': 'Retrain risk model',
    'ai-risk.model-card': 'Risk model status',
    'ai-risk.model-name': 'Model name',
    'ai-risk.feature-count': 'Feature count',
    'ai-risk.best-prediction': 'Best prediction',
    'ai-risk.risk-probability': 'Late risk',
    'ai-risk.risk-level': 'Risk level',
    'ai-risk.low-risk': 'Low risk',
    'ai-risk.medium-risk': 'Medium risk',
    'ai-risk.high-risk': 'High risk',
    'ai-risk.no-result': 'No risk estimate yet. Fill the invoice features and predict.',
    'ai-risk.load-error': 'Unable to load risk model information.',
    'clients.title': 'Clients',
    'clients.subtitle': 'Manage your clients by business.',
    'clients.business': 'Business',
    'clients.no-business': 'No business found. Create one in Settings.',
    'clients.name': 'Name',
    'clients.email': 'Email',
    'clients.phone': 'Phone',
    'clients.address': 'Address',
    'clients.tax': 'Tax ID',
    'clients.create': 'Create',
    'clients.edit': 'Edit',
    'clients.update': 'Update',
    'clients.cancel': 'Cancel',
    'clients.refresh': 'Refresh',
    'clients.list': 'List',
    'clients.none': 'No client.',
    'clients.delete-confirm': 'Delete {name}?',
    'expenses.title': 'Expenses',
    'expenses.subtitle': 'Track expenses by business.',
    'expenses.error-loading': 'Failed to load expenses.',
    'expenses.business': 'Business',
    'expenses.no-business': 'No business found. Create one in Settings.',
    'expenses.create-update': 'Create / Update',
    'expenses.readonly': 'Read only (Business Owner).',
    'expenses.description': 'Description',
    'expenses.amount': 'Amount',
    'expenses.date': 'Date',
    'expenses.status': 'Status',
    'expenses.receipt': 'Receipt URL (optional)',
    'expenses.none': 'No expense.',
    'expenses.delete-confirm': 'Delete this expense?',
    'expenses.error': 'Expense error',
    'expenses.delete-error': 'Delete error',
    'expenses.status.pending': 'PENDING',
    'expenses.status.approved': 'APPROVED',
    'expenses.status.rejected': 'REJECTED',
    'expenses.validation.description-length': 'Description must be between 3 and 255 characters.',
    'expenses.validation.amount-positive': 'Amount must be greater than 0.',
    'expenses.validation.date-required': 'Date is required.',
    'expenses.validation.receipt-invalid': 'Invalid receipt URL.',
    'expenses.for-employee': 'For (employee)',
    'expenses.select-employee': 'Select employee...',
    'settings.title': 'Settings',
    'settings.configuration': 'Configuration',
    'settings.company-profile': 'Company profile',
    'settings.security': 'Security',
    'settings.team-roles': 'Team and roles',
    'settings.businesses': 'Businesses',
    'settings.new-company': 'New Company',
    'settings.add-business': 'Add business',
    'settings.create-business-title': 'Create a New Business',
    'settings.create-business-desc': 'Fill in the details to add a business to {tenant}.',
    'settings.cancel': 'Cancel',
    'settings.save': 'Save changes',
    'settings.saving': 'Saving...',
    'settings.company-identity': 'Company identity',
    'settings.upload-logo': 'Upload logo',
    'settings.company-name': 'Company name',
    'settings.tax-id': 'Tax ID / Matricule',
    'settings.country': 'Country (auto)',
    'settings.phone': 'Phone',
    'settings.address': 'Address',
    'settings.active-business': 'Active business settings',
    'settings.business-name': 'Business name',
    'settings.currency': 'Currency',
    'settings.tax-rate': 'Default tax rate (%)',
    'settings.category': 'Category',
    'settings.security-questions': 'Security Questions',
    'settings.security-questions-desc': 'Add multiple questions to secure your account recovery.',
    'settings.request-company-title': 'Request a New Company',
    'settings.request-company-desc': 'Send a request to create a new tenant. Our team will review it.',
    'settings.send-request': 'Send Request',
    'settings.sending': 'Sending...',
    'settings.updated-success': 'Changes saved',
    'settings.business-updated': 'Business updated',
    'settings.created-success': 'Business created successfully',
    'settings.request-error': 'Error while sending the request',
    'settings.create-error': 'Error while creating',
    'settings.new-question': 'New Question',
    'settings.answer': 'Answer',
    'settings.add-question': 'Add Question',
    'settings.adding': 'Adding...',
    'settings.twofa': 'Two-Factor Authentication (2FA)',
    'settings.twofa-desc': 'Add an extra layer of security to your account using Google Authenticator.',
    'settings.status': 'Status',
    'settings.enabled': 'Enabled',
    'settings.disabled': 'Disabled',
    'settings.enable-2fa': 'Enable 2FA',
    'settings.generating': 'Generating...',
    'settings.set-up-2fa': 'Set up 2FA',
    'settings.scan-qr': 'Scan this QR code with your Google Authenticator app and enter the 6-digit code.',
    'settings.enter-code': 'Enter 6-digit Code',
    'settings.verify-enable': 'Verify & Enable',
    'settings.verifying': 'Verifying...',
    'employees.title': 'Team Hub',
    'employees.subtitle': 'Manage your team access and roles',
    'employees.new': 'New employee',
    'employees.total': 'Total Employees',
    'employees.active': 'Active Now',
    'employees.roles': 'Total Roles',
    'employees.month': 'Added this month',
    'employees.search': 'Search by name or email...',
    'employees.employee': 'Employee',
    'employees.role': 'Role',
    'employees.status': 'Status',
    'employees.added': 'Added on',
    'employees.actions': 'Actions',
    'employees.active-label': 'Active',
    'employees.inactive-label': 'Inactive',
    'employees.no-employee': 'No employee found',
    'employees.showing': 'Showing {current} of {total} employees',
    'employees.view': 'View',
    'employees.edit': 'Edit',
    'employees.delete': 'Delete',
    'employees.deleted-success': 'Employee deleted successfully',
    'employees.delete-error': 'Delete error',
    'employees.role.all': 'All Roles',
    'employees.role.admin': 'Admin',
    'employees.role.manager': 'Manager',
    'employees.role.accountant': 'Accountant',
    'employees.role.analyst': 'Analyst',
    'employees.role.hr': 'HR',
    'employees.role.team_member': 'Team Member',
    'employees.details': 'Employee details',
    'employees.name': 'Name',
    'employee.create-title': 'Create an employee',
    'employee.create-desc': 'Access information will be sent by email.',
    'employee.email': 'Email',
    'employee.first-name': 'First name',
    'employee.last-name': 'Last name',
    'employee.role': 'Role',
    'employee.create': 'Create',
    'employee.creating': 'Creating...',
    'employee.success': 'Employee account created. Login details sent by email.',
    'employee.error': 'Error while creating',
    'invoice.title': 'Invoices',
    'invoice.subtitle': 'Manage your invoices by business.',
    'invoice.error-loading': 'Failed to load invoices.',
    'invoice.company': 'Company',
    'invoice.business': 'Business',
    'invoice.create-update': 'Create / Update',
    'invoice.readonly': 'Read only (Business Owner).',
    'invoice.refresh': 'Refresh',
    'invoice.for-employee': 'For (employee)',
    'invoice.client': 'Client',
    'invoice.status': 'Status',
    'invoice.issue-date': 'Issue date',
    'invoice.due-date': 'Due date',
    'invoice.total': 'Total',
    'invoice.tax': 'Tax',
    'invoice.notes': 'Notes',
    'clients.validation.name-length': 'Client name must be between 2 and 80 characters.',
    'clients.validation.invalid-email': 'Invalid email address.',
    'clients.validation.invalid-phone': 'Invalid phone number.',
    'clients.validation.address-too-long': 'Address is too long.',
    'clients.validation.tax-too-long': 'Tax number is too long.',
    'invoice.none': 'No invoice.',
    'invoice.number': 'N°',
    'invoice.number-label': 'Invoice number',
    'invoice.file-label': 'Invoice file (PDF/image)',
    'invoice.status.draft': 'DRAFT',
    'invoice.status.sent': 'SENT',
    'invoice.status.paid': 'PAID',
    'invoice.status.overdue': 'OVERDUE',
    'invoice.status.canceled': 'CANCELED',
    'invoice.auto-status.label': 'Automatic status',
    'invoice.auto-status.hint-no-issue': 'Choose an issue date to determine whether the invoice is unpaid or overdue.',
    'invoice.auto-status.hint-no-due': 'Without a due date, the invoice stays as a draft until you define the payment term.',
    'invoice.auto-status.hint-overdue': 'The due date is in the past, so the invoice is considered overdue if no payment exists.',
    'invoice.auto-status.hint-future': 'The due date is still in the future, so the invoice is unpaid but not overdue yet.',
    'invoice.ai-risk.high': 'High risk',
    'invoice.ai-risk.low': 'Low risk',
    'invoice.ai-risk.select-client-hint': 'Select a client to compute the AI risk from its invoice history.',
    'invoice.select-client': 'Select client...',
    'invoice.ai-risk.confidence': 'Confidence',
    'invoice.validation.client-required': 'Client is required.',
    'invoice.validation.issue-date-required': 'Issue date is required.',
    'invoice.validation.due-date-after-issue': 'Due date must be after issue date.',
    'invoice.validation.total-positive': 'Total must be greater than 0.',
    'invoice.validation.tax-positive': 'Tax must be positive.',
    'common.ok': 'OK',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.upload': 'Upload',
    'invoice.notes-too-long': 'Notes are too long.',
    'invoice.ocr-failed': 'OCR failed.',
    'invoice.delete-confirm': 'Delete this invoice?',
    'invoice.error': 'Invoice error',
    'invoice.delete-error': 'Delete error',
    'invoice.issue': 'Issue',
    'invoice.due': 'Due',
    'invoice.actions': 'Actions',
    'reset.update': 'Update password',
    'admin.blocked-title': 'Blocked accounts',
    'admin.blocked-count': '{count} blocked',
    'admin.blocked-description': 'See currently locked users and unblock them manually when needed.',
    'admin.refresh': 'Refresh',
    'admin.loading': 'Loading',
    'admin.blocked-users': 'Blocked users',
    'admin.unlocking-soon': 'Unlocking soon',
    'admin.failed-attempts': 'Failed attempts total',
    'admin.no-blocked': 'No blocked accounts',
    'admin.all-accessible': 'All accounts are currently accessible.',
    'admin.left': 'left',
    'admin.company': 'Company',
    'admin.role': 'Role',
    'admin.attempts': 'Attempts',
    'admin.blocked-until': 'Blocked until {date}',
    'admin.unblock-now': 'Unblock now',
    'admin.unblock-title': 'Unblock this account?',
    'admin.unblock-description': 'This account is currently blocked until {date}. Manual unblocking will also reset the login attempts.',
    'admin.unblock-company': 'Company',
    'admin.time-left': 'Time left',
    'admin.cancel': 'Cancel',
    'admin.confirm-unblock': 'Unblock now',
    'admin.pending-registrations': 'Pending Registrations',
    'admin.pending-count': '{count} Pending',
    'admin.pending-description': 'Review and manage new business owner registration requests',
    'admin.total-pending': 'Total Pending',
    'admin.approved-today': 'Approved Today',
    'admin.rejected-today': 'Rejected Today',
    'admin.all-caught-up': 'All caught up!',
    'admin.no-pending': 'No pending registrations.',
    'admin.requested': 'Requested {time}',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.reject-registration': 'Reject Registration',
    'admin.reject-reason': 'Reason',
    'admin.reject-confirm': 'Reject',
    'admin.password-requests': 'Password Recovery Requests',
    'admin.password-requests-desc': 'Manual password reset requests from users',
    'admin.no-password-requests': 'No pending requests',
    'admin.password-requests-empty': 'All password recovery requests are processed.',
    'admin.requested-at': 'Requested {date}',
    'admin.approve-send-password': 'Approve & Send New Password',
    'admin.reject-request': 'Reject',
    'admin.confirm-password-reset': 'Are you sure you want to reset password for {email}? A new temporary password will be sent via email.',
    'admin.approved': 'Approved',
    'admin.password-sent': 'New password sent to user.',
    'admin.approve-failed': 'Failed to approve request.',
    'admin.rejected': 'Rejected',
    'admin.user-notified': 'User has been notified.',
    'admin.reject-failed': 'Failed to reject request.',
    'admin.rejection-reason': 'Reason for rejection:',
    'roles.title': 'Roles & permissions',
    'roles.subtitle': 'Manage access levels and permissions for each role',
    'roles.saving': 'Saving...',
    'roles.add-role': 'Add role',
    'roles.total': 'Total roles',
    'roles.permissions': 'Permissions',
    'roles.active-users': 'Active users',
    'roles.full-access': 'Full access',
    'roles.matrix': 'Permissions Matrix',
    'roles.permission': 'Permission',
    'roles.users-active': 'active users',
    'roles.super-admin-desc': 'Full control over the whole platform and all businesses.',
    'roles.admin-desc': 'High-level management of users and system settings.',
    'roles.owner-desc': 'Owner of a specific business with full access to company data.',
    'roles.business-owner-desc': 'Manages a specific business unit within a company.',
    'roles.custom-desc': 'Custom role for the organization.',
    'dashboard.loading': 'Loading dashboard statistics...',
    'dashboard.error-loading': 'Failed to load dashboard statistics.',
    'dashboard.retry': 'Retry',
    'dashboard.admin-only': 'Dashboard statistics are available for Admin and Business Owner roles.',
    'dashboard.metric.total-tenants': 'Total tenants',
    'dashboard.metric.total-businesses': 'Total businesses',
    'dashboard.metric.active-users': 'Active users',
    'dashboard.metric.pending-actions': 'Pending actions',
    'dashboard.metric.total-businesses-hint': '{count} businesses across the platform',
    'dashboard.metric.active-users-hint': '{count} accounts currently blocked',
    'dashboard.metric.pending-actions-hint': '{count} items requiring review',
    'dashboard.metric.invoiced-amount': 'Invoiced amount',
    'dashboard.metric.outstanding-amount': 'Outstanding amount',
    'dashboard.metric.expenses': 'Expenses',
    'dashboard.metric.invoices-hint': '{total} invoices across {businesses} businesses',
    'dashboard.metric.overdue-hint': '{count} overdue invoices',
    'dashboard.metric.clients-employees-hint': '{clients} clients and {employees} employees',
    'dashboard.cashflow.total-invoiced': 'Total invoiced',
    'dashboard.cashflow.paid': 'Paid',
    'dashboard.cashflow.outstanding': 'Outstanding',
    'dashboard.ops.clients': 'Clients',
    'dashboard.ops.employees': 'Employees',
    'dashboard.ops.overdue-invoices': 'Overdue invoices',
    'dashboard.col.activity': 'Activity',
    'dashboard.col.status': 'Status',
    'dashboard.col.date': 'Date',
    'dashboard.col.client': 'Client',
    'dashboard.col.amount': 'Amount',
    'dashboard.col.issued-at': 'Issued at',
    'dashboard.col.number': 'Number',
    'dashboard.col.description': 'Description',
    'dashboard.col.expense': 'Expense',
    'dashboard.col.tenant': 'Tenant',
    'dashboard.col.businesses': 'Businesses',
    'dashboard.col.users': 'Users',
    'dashboard.queue.pending-registrations': 'Pending registrations',
    'dashboard.queue.blocked-accounts': 'Blocked accounts',
    'dashboard.queue.password-resets': 'Password reset requests',
    'dashboard.scope.platform': 'Platform overview',
    'dashboard.scope.business': 'Business overview',
    'dashboard.scope.default': 'Dashboard',
    'dashboard.users-by-role': 'Users by role',
    'dashboard.organization-mix': 'Organization mix',
    'dashboard.total': 'Total',
    'dashboard.no-role-dist': 'No role distribution available.',
    'dashboard.operational-queues': 'Operational queues',
    'dashboard.pending-admin-actions': 'Pending admin actions',
    'dashboard.max-queue-hint': '{percent}% of max queue',
    'dashboard.tenant-portfolio': 'Tenant portfolio overview',
    'dashboard.tenant-portfolio-hint': 'Businesses and users by tenant',
    'dashboard.tenant': 'Tenant',
    'dashboard.businesses': 'Businesses',
    'dashboard.users': 'Users',
    'dashboard.no-tenant-coverage': 'No tenant coverage available.',
    'dashboard.tenant-leaderboard': 'Tenant leaderboard',
    'dashboard.live-tenant-coverage': 'Live tenant coverage',
    'dashboard.coverage': 'Coverage',
    'dashboard.recent-admin-activity': 'Recent admin activity',
    'dashboard.latest-platform-events': 'Latest platform events',
    'dashboard.financial-overview': 'Financial overview',
    'dashboard.cash-position': 'Cash position and receivables',
    'dashboard.no-cashflow': 'No financial breakdown available.',
    'dashboard.top-amount-hint': '{percent}% of top amount',
    'dashboard.invoice-status': 'Invoice status',
    'dashboard.collection-health': 'Collection health',
    'dashboard.invoices': 'Invoices',
    'dashboard.no-invoices': 'No invoices found yet.',
    'dashboard.expense-status': 'Expense status',
    'dashboard.expense-approval-mix': 'Expense approval mix',
    'dashboard.no-expenses': 'No expenses found yet.',
    'dashboard.top-clients': 'Top clients',
    'dashboard.revenue-concentration': 'Revenue concentration',
    'dashboard.top-client-hint': '{percent}% of top client',
    'dashboard.no-client-billing': 'No client billing data yet.',
    'dashboard.operations-pulse': 'Operations pulse',
    'dashboard.core-business-activity': 'Core business activity',
    'dashboard.current-tracked-value': 'Current tracked value',
    'dashboard.no-operations': 'No operations breakdown available.',
    'dashboard.latest-billing-activity': 'Latest billing activity',
    'dashboard.recent-expenses': 'Recent expenses',
    'dashboard.latest-spending-activity': 'Latest spending activity',
    'dashboard.revenue-distribution': 'Revenue distribution',
    'dashboard.by-client': 'By client',
    'dashboard.no-revenue-data': 'No revenue data available.',
    'dashboard.recent-activity-hint': 'Recent platform activity will appear here.',
    'common.notifications': 'Notifications',
    'common.business-owner': 'Business Owner',
    'common.user': 'User',
  },
  ar: {
    'common.loading': 'جارٍ التحميل',
    'common.please-wait': 'يرجى الانتظار أثناء معالجة الطلب.',
    'common.menu': 'القائمة',
    'common.settings': 'الإعدادات',
    'common.logout': 'تسجيل الخروج',
    'common.light': 'فاتح',
    'common.dark': 'داكن',
    'common.login': 'تسجيل الدخول',
    'common.register': 'إنشاء حساب',
    'common.back': 'رجوع',
    'common.email': 'البريد الإلكتروني',
    'common.password': 'كلمة المرور',
    'common.remember-me': 'تذكرني',
    'common.forgot-password': 'نسيت كلمة المرور؟',
    'common.sign-in': 'الدخول',
    'common.verifying': 'جارٍ التحقق...',
    'common.verify': 'تحقق',
    'common.welcome': 'مرحباً',
    'common.create-account': 'أنشئ حسابك',
    'common.company-name': 'اسم الشركة',
    'common.first-name': 'الاسم الأول',
    'common.last-name': 'اسم العائلة',
    'common.optional': 'اختياري',
    'common.terms': 'أوافق على شروط الاستخدام',
    'common.submit': 'إرسال',
    'common.dashboard': 'لوحة التحكم',
    'common.home': 'الرئيسية',
    'common.clients': 'العملاء',
    'common.expenses': 'المصاريف',
    'common.invoices': 'الفواتير',
    'common.team': 'الفريق',
    'common.ai-lab': 'مختبر الذكاء الاصطناعي',
    'common.pricing': 'الأسعار',
    'common.features': 'الميزات',
    'common.how-it-works': 'كيف يعمل',
    'common.why-taskflow': 'لماذا TaskFlow؟',
    'common.free-trial': 'تجربة مجانية لمدة 30 يوماً — بدون بطاقة بنكية',
    'common.start-now': 'ابدأ الآن',
    'common.get-started': 'ابدأ',
    'common.see-pricing': 'عرض الأسعار',
    'common.support': 'الدعم',
    'common.for-business': 'للشركات',
    'common.accountants': 'للمحاسبين',
    'common.account': 'الحساب',
    'common.all': 'الكل',
    'common.admin': 'مسؤول',
    'common.me': 'أنا',
    'common.error': 'خطأ',
    'common.unknown-error': 'خطأ غير معروف',
    'common.status.pending': 'معلق',
    'common.status.approved': 'مقبول',
    'common.status.rejected': 'مرفوض',
    'common.status.blocked': 'محظور',
    'common.status.active': 'نشط',
    'common.status.completed': 'مكتمل',
    'common.current-language': 'اللغة',
    'common.language-en': 'EN',
    'common.language-ar': 'AR',
    'common.show-password': 'إظهار كلمة المرور',
    'common.hide-password': 'إخفاء كلمة المرور',
    'common.toggle-theme': 'تبديل المظهر',
    'common.enter-email': 'أدخل بريدك الإلكتروني لبدء الاسترجاع.',
    'common.choose-method': 'اختر طريقة',
    'common.security-questions': 'أسئلة الأمان',
    'common.link-by-email': 'رابط عبر البريد الإلكتروني',
    'common.contact-admin': 'التواصل مع المدير',
    'common.new-password': 'كلمة مرور جديدة',
    'common.confirm-password': 'تأكيد كلمة المرور',
    'auth.login-to-space': 'سجّل الدخول للوصول إلى مساحة عملك.',
    'auth.email-placeholder': 'مثال: name@company.com',
    'auth.password-placeholder': 'كلمة المرور الخاصة بك',
    'auth.no-account': 'ليس لديك حساب بعد؟',
    'auth.twofa-title': 'التحقق الثنائي',
    'auth.twofa-description': 'أدخل الرمز المكوّن من 6 أرقام من تطبيق المصادقة الخاص بك.',
    'auth.verification-code': 'رمز التحقق',
    'auth.create-account-desc': 'تجربة مجانية لمدة 30 يوماً، بدون بطاقة 🎉',
    'auth.company-category': 'فئة الشركة (اختياري)',
    'auth.company-category-select': 'اختر فئة',
    'auth.category-retail': 'تجارة تجزئة',
    'auth.category-services': 'خدمات',
    'register.back-to-login': 'العودة إلى تسجيل الدخول',
    'register.sent': 'تم إرسال التسجيل',
    'register.first-name-placeholder': 'اسمك الأول',
    'register.last-name-placeholder': 'اسمك الأخير',
    'register.continue-with': 'أو المتابعة عبر',
    'auth.category-technology': 'تكنولوجيا',
    'auth.category-restaurant': 'مطعم',
    'auth.category-freelance': 'عمل حر',
    'auth.category-healthcare': 'الرعاية الصحية',
    'auth.category-education': 'التعليم',
    'auth.category-other': 'أخرى',
    'auth.company-placeholder': 'اسم الشركة',
    'auth.professional-email': 'البريد الإلكتروني المهني',
    'auth.accept-terms': 'أوافق على شروط الاستخدام',
    'auth.already-account': 'هل لديك حساب بالفعل؟',
    'auth.social-google': 'المتابعة عبر Google',
    'auth.social-facebook': 'المتابعة عبر Facebook',
    'auth.social-linkedin': 'المتابعة عبر LinkedIn',
    'auth.social-apple': 'المتابعة عبر Apple',
    'auth.otp-invalid': 'رمز التحقق غير صالح',
    'auth.secure-access': 'وصول آمن',
    'auth.google-error': 'خطأ أثناء الاتصال بـ Google.',
    'auth.google-loading': 'تسجيل الدخول عبر Google لم يكتمل بعد. يرجى المحاولة مرة أخرى.',
    'auth.validation.required': '{field} مطلوب.',
    'auth.validation.minlength': 'يجب أن يحتوي {field} على {count} أحرف على الأقل.',
    'auth.blocked-temporarily': 'الحساب محظور مؤقتًا.',
    'auth.pending-approval': 'حسابك بانتظار موافقة المدير.',
    'auth.invalid-credentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
    'auth.invalid-password': 'كلمة المرور غير صحيحة.',
    'auth.email-required': 'البريد المهني مطلوب.',
    'auth.invalid-email': 'يرجى إدخال عنوان بريد إلكتروني صالح.',
    'auth.accept-required': 'يجب أن توافق على شروط الاستخدام.',
    'auth.email-already-used': 'يوجد حساب بهذا البريد الإلكتروني بالفعل.',
    'auth.register-success-message': 'تم إرسال طلب التسجيل بنجاح.\nيرجى الانتظار، ستتلقى قريبًا بريدًا من المشرف العام\nيحتوي على بريدك الإلكتروني وكلمة المرور لتسجيل الدخول.',
    'home.hero-line1': 'إدارة ذكية.',
    'home.hero-line2': 'محلية. آمنة.',
    'home.hero-line3': 'تونسية.',
    'home.hero-description': 'أدر فواتيرك ومصاريفك وفريقك من منصة واحدة — مع سيادة كاملة على البيانات في تونس.',
    'forgot.title': 'نسيت كلمة المرور',
    'forgot.description': 'أدخل بريدك الإلكتروني لبدء الاسترجاع.',
    'forgot.step-choose': 'اختر طريقة',
    'forgot.step-choose-desc': 'كيف تريد إعادة تعيين كلمة المرور؟',
    'forgot.security-question': 'أسئلة الأمان',
    'forgot.security-question-desc': 'أجب عن الأسئلة المهيأة.',
    'forgot.email-link': 'رابط عبر البريد الإلكتروني',
    'forgot.email-link-desc': 'استلم رابط إعادة تعيين كلمة المرور.',
    'forgot.contact-admin': 'التواصل مع المدير',
    'forgot.contact-admin-desc': 'اطلب المساعدة من المدير الأعلى.',
    'forgot.contact-admin-error': 'حدث خطأ أثناء التواصل مع المدير.',
    'forgot.invalid-email': 'يرجى إدخال عنوان بريد إلكتروني صالح.',
    'forgot.email-not-found': 'البريد الإلكتروني غير موجود.',
    'forgot.email-sent-title': 'تم إرسال البريد الإلكتروني',
    'forgot.email-sent-message': 'تم إرسال رابط إعادة التعيين إلى عنوان بريدك الإلكتروني.',
    'forgot.request-sent-title': 'تم إرسال الطلب',
    'forgot.request-sent-message': 'تم إرسال طلبك إلى المشرف العام. ستتلقى إشعارًا قريبًا.',
    'forgot.answers-incorrect': 'إجابة واحدة أو أكثر غير صحيحة.',
    'forgot.reset-error': 'حدث خطأ أثناء إعادة تعيين كلمة المرور.',
    'forgot.new-password-title': 'كلمة مرور جديدة',
    'forgot.new-password-desc': 'أنشئ كلمة مرور جديدة وآمنة.',
    'forgot.success': 'نجاح!',
    'forgot.reset-success': 'تمت إعادة تعيين كلمة المرور بنجاح.',
    'forgot.redirection-countdown': 'سيتم تحويلك إلى صفحة تسجيل الدخول خلال {count} ثوانٍ...',
    'forgot.login-now': 'سجّل الدخول الآن',
    'forgot.loading': 'جارٍ التحميل...',
    'forgot.continue': 'متابعة',
    'forgot.verify': 'تحقق',
    'forgot.verifying': 'جارٍ التحقق...',
    'forgot.answer': 'إجابتك',
    'forgot.password-strength': 'القوة',
    'forgot.min-eight': '8 أحرف على الأقل',
    'forgot.uppercase': 'حرف كبير واحد',
    'forgot.lowercase': 'حرف صغير واحد',
    'forgot.number': 'رقم واحد',
    'forgot.special': 'حرف خاص واحد',
    'forgot.match': 'كلمات المرور متطابقة',
    'forgot.resetting': 'جارٍ إعادة التعيين...',
    'reset.missing-token': 'رمز إعادة التعيين مفقود.',
    'reset.success': 'تمت إعادة تعيين كلمة المرور بنجاح. جارٍ التحويل...',
    'change.title': 'تغيير كلمة المرور',
    'change.description': 'لأمانك، يرجى تعيين كلمة مرور جديدة.',
    'change.temporary': 'أنت تستخدم كلمة مرور مؤقتة. يرجى تغييرها الآن.',
    'change.current': 'كلمة المرور الحالية',
    'change.new': 'كلمة المرور الجديدة',
    'change.confirm': 'تأكيد كلمة المرور',
    'change.strength': 'القوة',
    'change.strength-weak': 'ضعيف',
    'change.strength-medium': 'متوسط',
    'change.strength-strong': 'قوي',
    'change.change-now': 'غيّر الآن',
    'change.please-change': 'يرجى تغييرها الآن.',
    'change.requirements': 'المتطلبات',
    'change.special': 'حرف خاص واحد',
    'change.success': 'تم تحديث كلمة المرور بنجاح. جارٍ التحويل...',
    'change.error': 'خطأ غير معروف',
    'onboarding.company-info': 'معلومات الشركة',
    'onboarding.your-business': 'نشاطك التجاري',
    'onboarding.complete-profile': 'أكمل ملف شركتك',
    'onboarding.profile-desc': 'ستظهر هذه المعلومات على الفواتير. تستغرق دقيقة واحدة.',
    'onboarding.company-name': 'اسم الشركة',
    'onboarding.set-during-reg': 'تم تحديده أثناء التسجيل',
    'onboarding.address': 'العنوان',
    'onboarding.address-placeholder': 'شارع الحبيب بورقيبة، المدينة...',
    'onboarding.country': 'البلد',
    'onboarding.phone': 'الهاتف',
    'onboarding.logo-url': 'رابط الشعار',
    'onboarding.logo-placeholder': 'https://yourlogo.com/logo.png',
    'onboarding.invalid-logo': 'رابط الصورة غير صالح',
    'onboarding.required': 'هذا الحقل مطلوب',
    'onboarding.save-continue': 'حفظ ومتابعة',
    'onboarding.saving': 'جارٍ الحفظ...',
    'onboarding.save-error': 'فشل الحفظ. حاول مرة أخرى.',
    'onboarding.create-business-title': 'أنشئ أول شركة لك',
    'onboarding.create-business-desc': 'يمكنك إضافة شركات أخرى لاحقاً من الإعدادات.',
    'onboarding.auto-country': 'تم الاختيار تلقائياً حسب بلدك',
    'onboarding.optional-later': 'اختياري - يمكنك إضافته لاحقاً',
    'onboarding.review-business': 'راجع نشاطك التجاري',
    'onboarding.create-go-dashboard': 'إنشاء النشاط والانتقال إلى لوحة التحكم',
    'onboarding.creating': 'جارٍ الإنشاء...',
    'onboarding.create-error': 'فشل إنشاء النشاط. حاول مرة أخرى.',
    'security.title': 'أسئلة الأمان',
    'security.description': 'استخدم هذه المعلومات لاستعادة الحساب.',
    'security.question': 'السؤال',
    'security.answer': 'الإجابة',
    'security.saved': 'تم حفظ أسئلة الأمان.',
    'security.save': 'حفظ',
    'security.saving': 'جارٍ الحفظ...',
    'security.error': 'خطأ أثناء الحفظ',
    'admin.load-registrations-error': 'فشل تحميل الطلبات المعلقة.',
    'home.business-feed': 'تغذية الأعمال',
    'home.more-info': 'مزيد من المعلومات متاحة',
    'home.insights': 'مؤشرات',
    'home.tab-accounting': 'المحاسبة',
    'home.tab-sales': 'المبيعات والتحصيل',
    'home.tab-marketing': 'التسويق',
    'home.tab-expenses': 'المصاريف والفواتير',
    'home.tab-hub': 'مركز العملاء',
    'home.customer-agent': 'وكيل العملاء',
    'home.accounting-agent': 'وكيل المحاسبة',
    'home.expense-agent': 'وكيل المصاريف',
    'home.client-agent': 'وكيل العملاء',
    'home.marketing-agent': 'وكيل التسويق',
    'home.email-agent': 'وكيل البريد',
    'home.seo-agent': 'وكيل SEO',
    'home.budget-agent': 'وكيل الميزانية',
    'home.vat-agent': 'وكيل الضريبة',
    'home.sales-agent': 'وكيل المبيعات',
    'home.transactions-categorized': 'تم تصنيف المعاملات',
    'home.sales-on-track': 'المبيعات عادت إلى المسار الصحيح',
    'home.new-leads-review': 'جهات جديدة جاهزة للمراجعة',
    'home.bills-processed': 'تمت معالجة الفواتير',
    'home.open-tickets': 'التذاكر المفتوحة',
    'home.processed-invoices': 'الفواتير المعالجة',
    'home.tracked': 'قيد التتبع',
    'home.new-leads': 'جهات مهتمة جديدة',
    'home.active-campaigns': 'الحملات النشطة',
    'home.sent-emails': 'الرسائل المرسلة',
    'home.new-visitors': 'زوار جدد',
    'home.pending-invoices': 'الفواتير المعلقة',
    'home.used-tnd': 'TND مستخدمة',
    'home.vat-tnd': 'TND ضريبة القيمة المضافة',
    'home.transactions': 'المعاملات',
    'home.tracked-tnd': 'TND قيد التتبع',
    'home.lead': 'جهة مهتمة',
    'home.chequing-account': 'الحساب الجاري',
    'home.mastercard': 'ماستركارد',
    'home.create-account-step': 'أنشئ حساباً',
    'home.create-account-desc': 'سجّل في بضع ثوانٍ.',
    'home.setup-company-step': 'أعدّ شركتك',
    'home.setup-company-desc': 'حدّد فرقك وإعداداتك.',
    'home.manage-step': 'أدر المهام والمالية',
    'home.manage-step-desc': 'تابع الأنشطة والفواتير والمصاريف.',
    'common.step': 'الخطوة',
    'home.revenue': 'الإيرادات',
    'home.expenses': 'المصاريف',
    'home.profit': 'الربح',
    'home.active-projects': 'المشاريع النشطة',
    'home.leads': 'الجهات المهتمة',
    'home.bank-accounts': 'الحسابات البنكية',
    'home.cash-flow-expenses': 'التدفق النقدي والمصاريف',
    'home.current-cash-balance': 'الرصيد النقدي الحالي',
    'home.infrastructure': 'البنية التحتية',
    'home.marketing': 'التسويق',
    'home.hr': 'الموارد البشرية',
    'home.other': 'أخرى',
    'home.data-in-tunisia': '🇹🇳 البيانات مستضافة في تونس',
    'home.compliance-guaranteed': 'الامتثال مضمون',
    'home.fast-onboarding': 'تأهيل سريع، إنتاجية من اليوم الأول.',
    'home.intuitive-ux': 'تجربة استخدام بديهية',
    'home.multi-tenant-security': 'عزل صارم لكل مستأجر، مع أفضل الممارسات.',
    'home.advanced-reports': 'مؤشرات، تصدير، وعروض مخصصة.',
    'home.your-data-stays': 'تبقى بياناتك في تونس. نقطة.',
    'home.tunisian-hosting': 'استضافة تونسية 100%',
    'home.hosting-desc': 'خوادم OVH تونس، دون أي نقل خارج الحدود',
    'home.inpdp': 'الامتثال لـ INPDP',
    'home.inpdp-desc': 'الاحترام الكامل للقانون الأساسي رقم 2004-63',
    'home.local-payment': 'الدفع المحلي',
    'home.payment-desc': 'تكامل مع البنوك التونسية وSobflous',
    'home.our-team': 'فريقنا',
    'home.try-free': 'جرّب TaskFlow مجاناً',
    'home.subscribe': 'اشترك',
    'home.tips': 'استقبل نصائحنا',
    'home.tips-desc': 'استقبل نصائحنا لإدارة شركتك بشكل أفضل',
    'home.thanks': 'شكراً، تم الاشتراك!',
    'home.plan-free': 'مجاني',
    'home.plan-pro': 'احترافي',
    'home.plan-enterprise': 'المؤسسات',
    'home.price-free': '0 دينار تونسي',
    'home.price-pro': '49 دينار تونسي / شهر',
    'home.price-enterprise': 'تواصل معنا',
    'home.sso': 'تسجيل دخول موحّد',
    'home.advanced-integrations': 'تكاملات متقدمة',
    'home.secure-user-friendly': 'آمن وسهل الاستخدام',
    'home.banking-made-hassle-free': 'الخدمات البنكية دون تعقيد',
    'home.helpful-banking-support': 'دعم بنكي مفيد',
    'home.account-holder-since-2015': 'عميل منذ 2015',
    'home.account-holder-since-2021': 'عميل منذ 2021',
    'home.account-holder-since-2020': 'عميل منذ 2020',
    'home.bank-interest': 'فوائد بنكية',
    'home.crypto-currency': 'العملة الرقمية',
    'home.share-market': 'سوق الأسهم',
    'home.contact': 'اتصال',
    'home.faq': 'الأسئلة الشائعة',
    'home.privacy': 'سياسة الخصوصية',
    'register.tunisian-hosted': '🇹🇳 البيانات مستضافة في تونس • الامتثال لـ INPDP مضمون',
    'settings.security-added': 'تمت إضافة سؤال الأمان',
    'dashboard.title': 'لوحة التحكم',
    'dashboard.subtitle': 'نظرة سريعة على نشاطك.',
    'dashboard.period': 'هذا الشهر',
    'dashboard.revenue': 'الإيرادات',
    'dashboard.expenses': 'المصاريف',
    'dashboard.profit': 'الربح',
    'dashboard.performance': 'الأداء',
    'dashboard.shortcuts': 'اختصارات',
    'dashboard.recent-invoices': 'الفواتير الأخيرة',
    'dashboard.latest-activities': 'آخر الأنشطة',
    'dashboard.monthly-change': 'مقارنة بالشهر الماضي',
    'dashboard.margin': 'الهامش',
    'dashboard.recent': 'النشاط الأخير',
    'dashboard.col-client': 'العميل',
    'dashboard.col-amount': 'المبلغ',
    'dashboard.col-status': 'الحالة',
    'dashboard.col-issued': 'تاريخ الإصدار',
    'ai.title': 'مصنف المصاريف بالذكاء الاصطناعي',
    'ai.subtitle': 'درّب واختبر النموذج المبني من الصفر على أوصاف المصاريف.',
    'ai.input-label': 'الوصف المراد تصنيفه',
    'ai.input-placeholder': 'مثال: اشتراك شهري في Google Workspace لفريق المبيعات',
    'ai.predict': 'صنّف',
    'ai.retrain': 'أعد تدريب النموذج',
    'ai.model-card': 'حالة النموذج',
    'ai.training-accuracy': 'دقة التدريب',
    'ai.training-examples': 'أمثلة التدريب',
    'ai.vocabulary': 'حجم المفردات',
    'ai.top-label': 'أفضل توقع',
    'ai.confidence': 'مستوى الثقة',
    'ai.matched-tokens': 'الرموز المطابقة',
    'ai.no-result': 'لا يوجد توقع بعد. أدخل وصفاً ثم صنّفه.',
    'ai.load-error': 'تعذر تحميل معلومات النموذج.',
    'common.ai-risk': 'خطر الفاتورة',
    'ai-risk.title': 'نموذج تقدير تأخر دفع الفاتورة',
    'ai-risk.subtitle': 'تقدير خطر تأخر دفع الفاتورة اعتمادًا على خصائص الفاتورة وسجل العميل.',
    'ai-risk.client-context': 'سياق العميل',
    'ai-risk.business': 'الشركة',
    'ai-risk.client': 'العميل',
    'ai-risk.select-business': 'اختر شركة',
    'ai-risk.select-client': 'اختر عميلًا',
    'ai-risk.auto-fill-note': 'اختر عميلًا وسيتم ملء الحقول تلقائيًا من تاريخ فواتيره.',
    'ai-risk.no-client-data': 'لم يتم اختيار عميل بعد. اختر شركة وعميلًا لملء الخصائص تلقائيًا.',
    'ai-risk.input-label': 'خصائص الفاتورة',
    'ai-risk.amount': 'المبلغ',
    'ai-risk.due-days': 'مدة الدفع (أيام)',
    'ai-risk.client-late-ratio': 'نسبة التأخر لدى العميل',
    'ai-risk.previous-late-count': 'الفواتير المتأخرة السابقة',
    'ai-risk.open-invoices': 'الفواتير المفتوحة',
    'ai-risk.total-invoices': 'إجمالي الفواتير',
    'ai-risk.paid-invoices': 'الفواتير المدفوعة',
    'ai-risk.late-invoices': 'الفواتير المدفوعة متأخرة',
    'ai-risk.late-ratio': 'نسبة التأخر',
    'ai-risk.latest-amount': 'آخر مبلغ فاتورة مسجل',
    'ai-risk.predict': 'تقدير الخطر',
    'ai-risk.retrain': 'إعادة تدريب نموذج الخطر',
    'ai-risk.model-card': 'حالة نموذج الخطر',
    'ai-risk.model-name': 'اسم النموذج',
    'ai-risk.feature-count': 'عدد الخصائص',
    'ai-risk.best-prediction': 'أفضل نتيجة',
    'ai-risk.risk-probability': 'خطر التأخر',
    'ai-risk.risk-level': 'مستوى الخطر',
    'ai-risk.low-risk': 'خطر منخفض',
    'ai-risk.medium-risk': 'خطر متوسط',
    'ai-risk.high-risk': 'خطر مرتفع',
    'ai-risk.no-result': 'لا توجد تقديرات بعد. املأ خصائص الفاتورة ثم قم بالتقدير.',
    'ai-risk.load-error': 'تعذر تحميل معلومات نموذج الخطر.',
    'clients.title': 'العملاء',
    'clients.subtitle': 'أدر عملاءك حسب الشركة.',
    'clients.business': 'الشركة',
    'clients.no-business': 'لم يتم العثور على شركة. أنشئ واحدة في الإعدادات.',
    'clients.name': 'الاسم',
    'clients.email': 'البريد الإلكتروني',
    'clients.phone': 'الهاتف',
    'clients.address': 'العنوان',
    'clients.tax': 'المعرف الضريبي',
    'clients.create': 'إنشاء',
    'clients.edit': 'تعديل',
    'clients.update': 'تحديث',
    'clients.cancel': 'إلغاء',
    'clients.refresh': 'تحديث',
    'clients.list': 'القائمة',
    'clients.none': 'لا يوجد عميل.',
    'clients.delete-confirm': 'حذف {name}؟',
    'expenses.title': 'المصاريف',
    'expenses.subtitle': 'تتبع المصاريف حسب الشركة.',
    'expenses.error-loading': 'فشل تحميل المصاريف.',
    'expenses.business': 'الشركة',
    'expenses.no-business': 'لم يتم العثور على شركة. أنشئ واحدة في الإعدادات.',
    'expenses.create-update': 'إنشاء / تحديث',
    'expenses.readonly': 'للقراءة فقط (صاحب الشركة).',
    'expenses.description': 'الوصف',
    'expenses.amount': 'المبلغ',
    'expenses.date': 'التاريخ',
    'expenses.status': 'الحالة',
    'expenses.receipt': 'رابط الإيصال (اختياري)',
    'expenses.none': 'لا توجد مصاريف.',
    'expenses.delete-confirm': 'حذف هذه المصروفات؟',
    'expenses.error': 'خطأ في المصروفات',
    'expenses.delete-error': 'خطأ أثناء الحذف',
    'expenses.status.pending': 'معلق',
    'expenses.status.approved': 'مقبول',
    'expenses.status.rejected': 'مرفوض',
    'expenses.validation.description-length': 'يجب أن يكون الوصف بين 3 و 255 حرفاً.',
    'expenses.validation.amount-positive': 'يجب أن يكون المبلغ أكبر من 0.',
    'expenses.validation.date-required': 'التاريخ مطلوب.',
    'expenses.validation.receipt-invalid': 'رابط الإيصال غير صالح.',
    'expenses.for-employee': 'لـ (موظف)',
    'expenses.select-employee': 'اختر موظفاً...',
    'settings.title': 'الإعدادات',
    'settings.configuration': 'التهيئة',
    'settings.company-profile': 'ملف الشركة',
    'settings.security': 'الأمان',
    'settings.team-roles': 'الفريق والصلاحيات',
    'settings.businesses': 'الشركات',
    'settings.new-company': 'شركة جديدة',
    'settings.add-business': 'إضافة شركة',
    'settings.create-business-title': 'إنشاء شركة جديدة',
    'settings.create-business-desc': 'املأ التفاصيل لإضافة شركة إلى {tenant}.',
    'settings.cancel': 'إلغاء',
    'settings.save': 'حفظ التغييرات',
    'settings.saving': 'جارٍ الحفظ...',
    'settings.company-identity': 'هوية الشركة',
    'settings.upload-logo': 'رفع الشعار',
    'settings.company-name': 'اسم الشركة',
    'settings.tax-id': 'المعرف الضريبي / matricule',
    'settings.country': 'البلد (تلقائي)',
    'settings.phone': 'الهاتف',
    'settings.address': 'العنوان',
    'settings.active-business': 'إعدادات الشركة النشطة',
    'settings.business-name': 'اسم الشركة',
    'settings.currency': 'العملة',
    'settings.tax-rate': 'نسبة الضريبة الافتراضية (%)',
    'settings.category': 'الفئة',
    'settings.security-questions': 'أسئلة الأمان',
    'settings.security-questions-desc': 'أضف عدة أسئلة لتأمين استعادة الحساب.',
    'settings.request-company-title': 'طلب شركة جديدة',
    'settings.request-company-desc': 'أرسل طلبًا لإنشاء مستأجر جديد. سيقوم فريقنا بمراجعته.',
    'settings.send-request': 'إرسال الطلب',
    'settings.sending': 'جارٍ الإرسال...',
    'settings.updated-success': 'تم حفظ التغييرات',
    'settings.business-updated': 'تم تحديث النشاط التجاري',
    'settings.created-success': 'تم إنشاء النشاط التجاري بنجاح',
    'settings.request-error': 'خطأ أثناء إرسال الطلب',
    'settings.create-error': 'خطأ أثناء الإنشاء',
    'settings.new-question': 'سؤال جديد',
    'settings.answer': 'الإجابة',
    'settings.add-question': 'إضافة سؤال',
    'settings.adding': 'جارٍ الإضافة...',
    'settings.twofa': 'المصادقة الثنائية (2FA)',
    'settings.twofa-desc': 'أضف طبقة إضافية من الأمان باستخدام Google Authenticator.',
    'settings.status': 'الحالة',
    'settings.enabled': 'مفعل',
    'settings.disabled': 'معطل',
    'settings.enable-2fa': 'تفعيل 2FA',
    'settings.generating': 'جارٍ الإنشاء...',
    'settings.set-up-2fa': 'إعداد 2FA',
    'settings.scan-qr': 'امسح رمز QR هذا بتطبيق Google Authenticator وأدخل الرمز المكون من 6 أرقام.',
    'settings.enter-code': 'أدخل رمزًا من 6 أرقام',
    'settings.verify-enable': 'تحقق وفعّل',
    'settings.verifying': 'جارٍ التحقق...',
    'employees.title': 'مركز الفريق',
    'employees.subtitle': 'أدر وصول فريقك وصلاحياته',
    'employees.new': 'موظف جديد',
    'employees.total': 'إجمالي الموظفين',
    'employees.active': 'النشطون الآن',
    'employees.roles': 'إجمالي الأدوار',
    'employees.month': 'تمت الإضافة هذا الشهر',
    'employees.search': 'ابحث بالاسم أو البريد الإلكتروني...',
    'employees.employee': 'الموظف',
    'employees.role': 'الدور',
    'employees.status': 'الحالة',
    'employees.added': 'أضيف في',
    'employees.actions': 'الإجراءات',
    'employees.active-label': 'نشط',
    'employees.inactive-label': 'غير نشط',
    'employees.no-employee': 'لم يتم العثور على موظف',
    'employees.showing': 'عرض {current} من أصل {total} موظفاً',
    'employees.view': 'عرض',
    'employees.edit': 'تعديل',
    'employees.delete': 'حذف',
    'employees.deleted-success': 'تم حذف الموظف بنجاح',
    'employees.delete-error': 'خطأ أثناء الحذف',
    'employees.role.all': 'جميع الأدوار',
    'employees.role.admin': 'مدير',
    'employees.role.manager': 'مسؤول',
    'employees.role.accountant': 'محاسب',
    'employees.role.analyst': 'محلل',
    'employees.role.hr': 'موارد بشرية',
    'employees.role.team_member': 'عضو فريق',
    'employees.details': 'تفاصيل الموظف',
    'employees.name': 'الاسم',
    'employee.create-title': 'إنشاء موظف',
    'employee.create-desc': 'سيتم إرسال معلومات الوصول عبر البريد الإلكتروني.',
    'employee.email': 'البريد الإلكتروني',
    'employee.first-name': 'الاسم الأول',
    'employee.last-name': 'اسم العائلة',
    'employee.role': 'الدور',
    'employee.create': 'إنشاء',
    'employee.creating': 'جارٍ الإنشاء...',
    'employee.success': 'تم إنشاء حساب الموظف. تم إرسال بيانات الدخول عبر البريد الإلكتروني.',
    'employee.error': 'خطأ أثناء الإنشاء',
    'invoice.title': 'الفواتير',
    'invoice.subtitle': 'أدر فواتيرك حسب الشركة.',
    'invoice.error-loading': 'فشل تحميل الفواتير.',
    'invoice.company': 'المؤسسة',
    'invoice.business': 'الشركة',
    'invoice.create-update': 'إنشاء / تحديث',
    'invoice.readonly': 'للقراءة فقط (صاحب الشركة).',
    'invoice.refresh': 'تحديث',
    'invoice.for-employee': 'لـ (موظف)',
    'invoice.client': 'العميل',
    'invoice.status': 'الحالة',
    'invoice.issue-date': 'تاريخ الإصدار',
    'invoice.due-date': 'تاريخ الاستحقاق',
    'invoice.total': 'الإجمالي',
    'invoice.tax': 'الضريبة',
    'invoice.notes': 'ملاحظات',
    'invoice.none': 'لا توجد فاتورة.',
    'clients.validation.name-length': 'يجب أن يكون اسم العميل بين 2 و 80 حرفاً.',
    'clients.validation.invalid-email': 'عنوان بريد إلكتروني غير صالح.',
    'clients.validation.invalid-phone': 'رقم هاتف غير صالح.',
    'clients.validation.address-too-long': 'العنوان طويل جداً.',
    'clients.validation.tax-too-long': 'الرقم الضريبي طويل جداً.',
    'invoice.number': 'رقم',
    'invoice.number-label': 'رقم الفاتورة',
    'invoice.file-label': 'ملف الفاتورة (PDF/صورة)',
    'invoice.status.draft': 'مسودة',
    'invoice.status.sent': 'مرسل',
    'invoice.status.paid': 'مدفوع',
    'invoice.status.overdue': 'متأخر',
    'invoice.status.canceled': 'ملغى',
    'invoice.auto-status.label': 'الحالة التلقائية',
    'invoice.auto-status.hint-no-issue': 'اختر تاريخ الإصدار لتحديد ما إذا كانت الفاتورة غير مدفوعة أو متأخرة.',
    'invoice.auto-status.hint-no-due': 'بدون تاريخ استحقاق، تظل الفاتورة مسودة حتى تحدد شروط الدفع.',
    'invoice.auto-status.hint-overdue': 'تاريخ الاستحقاق في الماضي، لذا تعتبر الفاتورة متأخرة إذا لم يوجد دفع.',
    'invoice.auto-status.hint-future': 'تاريخ الاستحقاق لا يزال في المستقبل، لذا فإن الفاتورة غير مدفوعة ولكنها ليست متأخرة بعد.',
    'invoice.ai-risk.high': 'مخاطر عالية',
    'invoice.ai-risk.low': 'مخاطر منخفضة',
    'invoice.ai-risk.select-client-hint': 'اختر عميلاً لحساب مخاطر الذكاء الاصطناعي من سجل فواتيره.',
    'invoice.select-client': 'اختر عميلاً...',
    'invoice.ai-risk.confidence': 'الثقة',
    'invoice.validation.client-required': 'العميل مطلوب.',
    'invoice.validation.issue-date-required': 'تاريخ الإصدار مطلوب.',
    'invoice.validation.due-date-after-issue': 'يجب أن يكون تاريخ الاستحقاق بعد تاريخ الإصدار.',
    'invoice.validation.total-positive': 'يجب أن يكون المجموع أكبر من 0.',
    'invoice.validation.tax-positive': 'يجب أن تكون الضريبة إيجابية.',
    'invoice.delete-confirm': 'حذف هذه الفاتورة؟',
    'invoice.error': 'خطأ في الفاتورة',
    'invoice.delete-error': 'خطأ في الحذف',
    'common.ok': 'موافق',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.upload': 'تحميل',
    'invoice.notes-too-long': 'الملاحظات طويلة جداً.',
    'invoice.ocr-failed': 'فشل التعرف الضوئي على الحروف.',
    'invoice.issue': 'إصدار',
    'invoice.due': 'الاستحقاق',
    'invoice.actions': 'الإجراءات',
    'reset.update': 'تحديث كلمة المرور',
    'admin.blocked-title': 'الحسابات المحظورة',
    'admin.blocked-count': 'محظور {count}',
    'admin.blocked-description': 'عرض المستخدمين المقفلين حالياً وإلغاء الحظر يدوياً عند الحاجة.',
    'admin.refresh': 'تحديث',
    'admin.loading': 'جارٍ التحميل',
    'admin.blocked-users': 'المستخدمون المحظورون',
    'admin.unlocking-soon': 'سيتم فك الحظر قريباً',
    'admin.failed-attempts': 'إجمالي المحاولات الفاشلة',
    'admin.no-blocked': 'لا توجد حسابات محظورة',
    'admin.all-accessible': 'جميع الحسابات متاحة حالياً.',
    'admin.left': 'متبقٍ',
    'admin.company': 'الشركة',
    'admin.role': 'الدور',
    'admin.attempts': 'المحاولات',
    'admin.blocked-until': 'محظور حتى {date}',
    'admin.unblock-now': 'فك الحظر الآن',
    'admin.unblock-title': 'فك حظر هذا الحساب؟',
    'admin.unblock-description': 'هذا الحساب محظور حالياً حتى {date}. فك الحظر يدوياً سيعيد أيضاً ضبط محاولات تسجيل الدخول.',
    'admin.unblock-company': 'الشركة',
    'admin.time-left': 'الوقت المتبقي',
    'admin.cancel': 'إلغاء',
    'admin.confirm-unblock': 'فك الحظر الآن',
    'admin.pending-registrations': 'الطلبات المعلّقة',
    'admin.pending-count': 'معلّق {count}',
    'admin.pending-description': 'مراجعة وإدارة طلبات تسجيل أصحاب الأعمال الجدد',
    'admin.total-pending': 'إجمالي المعلّق',
    'admin.approved-today': 'تمت الموافقة اليوم',
    'admin.rejected-today': 'تم الرفض اليوم',
    'admin.all-caught-up': 'لا توجد عناصر جديدة!',
    'admin.no-pending': 'لا توجد طلبات معلّقة.',
    'admin.requested': 'تم الطلب منذ {time}',
    'admin.approve': 'موافقة',
    'admin.reject': 'رفض',
    'admin.reject-registration': 'رفض التسجيل',
    'admin.reject-reason': 'السبب',
    'admin.reject-confirm': 'رفض',
    'admin.password-requests': 'طلبات استرجاع كلمة المرور',
    'admin.password-requests-desc': 'طلبات إعادة تعيين كلمة المرور يدوياً من المستخدمين',
    'admin.no-password-requests': 'لا توجد طلبات معلّقة',
    'admin.password-requests-empty': 'تمت معالجة جميع طلبات استرجاع كلمة المرور.',
    'admin.requested-at': 'تم الطلب في {date}',
    'admin.approve-send-password': 'موافقة وإرسال كلمة مرور جديدة',
    'admin.reject-request': 'رفض',
    'admin.confirm-password-reset': 'هل تريد فعلاً إعادة تعيين كلمة المرور لـ {email}؟ سيتم إرسال كلمة مرور مؤقتة جديدة عبر البريد الإلكتروني.',
    'admin.approved': 'تمت الموافقة',
    'admin.password-sent': 'تم إرسال كلمة المرور الجديدة للمستخدم.',
    'admin.approve-failed': 'فشل قبول الطلب.',
    'admin.rejected': 'تم الرفض',
    'admin.user-notified': 'تم إشعار المستخدم.',
    'admin.reject-failed': 'فشل رفض الطلب.',
    'admin.rejection-reason': 'سبب الرفض:',
    'roles.title': 'الأدوار والصلاحيات',
    'roles.subtitle': 'إدارة مستويات الوصول والصلاحيات لكل دور',
    'roles.saving': 'جارٍ الحفظ...',
    'roles.add-role': 'إضافة دور',
    'roles.total': 'إجمالي الأدوار',
    'roles.permissions': 'الصلاحيات',
    'roles.active-users': 'المستخدمون النشطون',
    'roles.full-access': 'وصول كامل',
    'roles.matrix': 'مصفوفة الصلاحيات',
    'roles.permission': 'الصلاحية',
    'roles.users-active': 'مستخدمين نشطين',
    'roles.super-admin-desc': 'تحكم كامل في المنصة وكل الشركات.',
    'roles.admin-desc': 'إدارة عالية المستوى للمستخدمين وإعدادات النظام.',
    'roles.owner-desc': 'مالك شركة محددة مع وصول كامل لبياناتها.',
    'roles.business-owner-desc': 'يدير وحدة تجارية محددة داخل شركة.',
    'roles.custom-desc': 'دور مخصص داخل المؤسسة.',
    'dashboard.loading': 'جارٍ تحميل إحصائيات لوحة التحكم...',
    'dashboard.error-loading': 'فشل تحميل إحصائيات لوحة التحكم.',
    'dashboard.retry': 'إعادة المحاولة',
    'dashboard.admin-only': 'إحصائيات لوحة التحكم متاحة لأدوار المدير وصاحب العمل فقط.',
    'dashboard.metric.total-tenants': 'إجمالي المستأجرين',
    'dashboard.metric.total-businesses': 'إجمالي الشركات',
    'dashboard.metric.active-users': 'المستخدمون النشطون',
    'dashboard.metric.pending-actions': 'الإجراءات المعلقة',
    'dashboard.metric.total-businesses-hint': '{count} شركات عبر المنصة',
    'dashboard.metric.active-users-hint': '{count} حسابات محظورة حالياً',
    'dashboard.metric.pending-actions-hint': '{count} عناصر تتطلب المراجعة',
    'dashboard.metric.invoiced-amount': 'المبلغ المفوتر',
    'dashboard.metric.outstanding-amount': 'المبلغ المستحق',
    'dashboard.metric.expenses': 'المصاريف',
    'dashboard.metric.invoices-hint': '{total} فواتير عبر {businesses} شركات',
    'dashboard.metric.overdue-hint': '{count} فواتير متأخرة',
    'dashboard.metric.clients-employees-hint': '{clients} عملاء و {employees} موظفين',
    'dashboard.cashflow.total-invoiced': 'إجمالي المفوتر',
    'dashboard.cashflow.paid': 'تم الدفع',
    'dashboard.cashflow.outstanding': 'مستحق',
    'dashboard.ops.clients': 'العملاء',
    'dashboard.ops.employees': 'الموظفين',
    'dashboard.ops.overdue-invoices': 'الفواتير المتأخرة',
    'dashboard.col.activity': 'النشاط',
    'dashboard.col.status': 'الحالة',
    'dashboard.col.date': 'التاريخ',
    'dashboard.col.client': 'العميل',
    'dashboard.col.amount': 'المبلغ',
    'dashboard.col.issued-at': 'صدر في',
    'dashboard.col.number': 'الرقم',
    'dashboard.col.description': 'الوصف',
    'dashboard.col.expense': 'المصاريف',
    'dashboard.col.tenant': 'المستأجر',
    'dashboard.col.businesses': 'الشركات',
    'dashboard.col.users': 'المستخدمين',
    'dashboard.queue.pending-registrations': 'التسجيلات المعلقة',
    'dashboard.queue.blocked-accounts': 'الحسابات المحظورة',
    'dashboard.queue.password-resets': 'طلبات إعادة تعيين كلمة المرور',
    'dashboard.scope.platform': 'نظرة عامة على المنصة',
    'dashboard.scope.business': 'نظرة عامة على الشركة',
    'dashboard.scope.default': 'لوحة التحكم',
    'dashboard.users-by-role': 'المستخدمون حسب الدور',
    'dashboard.organization-mix': 'مزيج المؤسسة',
    'dashboard.total': 'الإجمالي',
    'dashboard.no-role-dist': 'لا يوجد توزيع للأدوار متاح.',
    'dashboard.operational-queues': 'قوائم العمليات',
    'dashboard.pending-admin-actions': 'إجراءات المدير المعلقة',
    'dashboard.max-queue-hint': '{percent}% من الحد الأقصى للقائمة',
    'dashboard.tenant-portfolio': 'نظرة عامة على محفظة المستأجرين',
    'dashboard.tenant-portfolio-hint': 'الشركات والمستخدمون حسب المستأجر',
    'dashboard.tenant': 'المستأجر',
    'dashboard.businesses': 'الشركات',
    'dashboard.users': 'المستخدمون',
    'dashboard.no-tenant-coverage': 'لا توجد تغطية للمستأجر متاحة.',
    'dashboard.tenant-leaderboard': 'قائمة متصدري المستأجرين',
    'dashboard.live-tenant-coverage': 'تغطية المستأجر المباشرة',
    'dashboard.coverage': 'التغطية',
    'dashboard.recent-admin-activity': 'نشاط المدير الأخير',
    'dashboard.latest-platform-events': 'آخر أحداث المنصة',
    'dashboard.financial-overview': 'نظرة عامة مالية',
    'dashboard.cash-position': 'المركز النقدي والذمم المدينة',
    'dashboard.no-cashflow': 'لا يتوفر تحليل مالي.',
    'dashboard.top-amount-hint': '{percent}% من أعلى مبلغ',
    'dashboard.invoice-status': 'حالة الفواتير',
    'dashboard.collection-health': 'صحة التحصيل',
    'dashboard.invoices': 'الفواتير',
    'dashboard.no-invoices': 'لم يتم العثور على فواتير بعد.',
    'dashboard.expense-status': 'حالة المصاريف',
    'dashboard.expense-approval-mix': 'مزيج الموافقة على المصاريف',
    'dashboard.no-expenses': 'لم يتم العثور على مصاريف بعد.',
    'dashboard.top-clients': 'كبار العملاء',
    'dashboard.revenue-concentration': 'تركيز الإيرادات',
    'dashboard.top-client-hint': '{percent}% من أعلى عميل',
    'dashboard.no-client-billing': 'لا توجد بيانات فوترة للعملاء بعد.',
    'dashboard.operations-pulse': 'نبض العمليات',
    'dashboard.core-business-activity': 'نشاط العمل الأساسي',
    'dashboard.current-tracked-value': 'القيمة المتتبعة الحالية',
    'dashboard.no-operations': 'لا يتوفر تحليل للعمليات.',
    'dashboard.latest-billing-activity': 'آخر نشاط فوترة',
    'dashboard.recent-expenses': 'المصاريف الأخيرة',
    'dashboard.latest-spending-activity': 'آخر نشاط إنفاق',
    'dashboard.revenue-distribution': 'توزيع الإيرادات',
    'dashboard.by-client': 'حسب العميل',
    'dashboard.no-revenue-data': 'لا تتوفر بيانات الإيرادات.',
    'dashboard.recent-activity-hint': 'ستظهر أنشطة المنصة الأخيرة هنا.',
    'common.notifications': 'الإشعارات',
    'common.business-owner': 'صاحب عمل',
    'common.user': 'مستخدم',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly _language = signal<AppLanguage>('en');
  readonly language = this._language.asReadonly();
  readonly isArabic = computed(() => this._language() === 'ar');

  init(): void {
    const initial = this.getInitialLanguage();
    this.setLanguage(initial, false);
  }

  setLanguage(language: AppLanguage, persist = true): void {
    this._language.set(language);
    this.applyToDocument(language);

    if (persist && typeof localStorage !== 'undefined') {
      try {
        localStorage.setItem(STORAGE_KEY, language);
      } catch {}
    }
  }

  toggle(): void {
    this.setLanguage(this._language() === 'en' ? 'ar' : 'en');
  }

  translate(key: string, params?: Record<string, string | number>): string {
    const template = TRANSLATIONS[this._language()][key] ?? TRANSLATIONS.en[key] ?? key;

    if (!params) {
      return template;
    }

    return Object.entries(params).reduce((text, [paramKey, paramValue]) => {
      return text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(paramValue));
    }, template);
  }

  private getInitialLanguage(): AppLanguage {
    if (typeof window === 'undefined') return 'en';

    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved === 'en' || saved === 'ar') return saved;
    } catch {}

    try {
      const browserLanguage = window.navigator.language?.toLowerCase() ?? 'en';
      return browserLanguage.startsWith('ar') ? 'ar' : 'en';
    } catch {
      return 'en';
    }
  }

  private applyToDocument(language: AppLanguage): void {
    if (typeof document === 'undefined') return;

    const root = document.documentElement;
    root.setAttribute('lang', language === 'ar' ? 'ar' : 'en');
    root.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr');
  }
}