export enum Role {
  SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
  BUSINESS_OWNER = 'ROLE_BUSINESS_OWNER',
  BUSINESS_ADMIN = 'ROLE_BUSINESS_ADMIN',
  ACCOUNTANT = 'ROLE_ACCOUNTANT',
  TEAM_MEMBER = 'ROLE_TEAM_MEMBER',
  CLIENT = 'ROLE_CLIENT',
}
