import os
import uuid
import random
from datetime import datetime, timedelta
import pandas as pd
from sqlalchemy import text
from database import invoice_engine

def seed_invoices():
    business_id = '6f0e41ce-df82-4a5b-b6f6-2706bec7dbc2'
    
    # Try to find an existing client ID
    with invoice_engine.connect() as conn:
        result = conn.execute(text('SELECT "clientId" FROM "Invoice" WHERE "businessId" = :bid LIMIT 1'), {'bid': business_id}).fetchone()
        client_id = result[0] if result else str(uuid.uuid4())
    
    print(f"Seeding invoices for business {business_id} with client {client_id}...")

    invoices = []
    now = datetime.now()
    base_revenue = 12000.0

    # Seed data for the last 12 months
    for month_offset in range(11, -1, -1):
        date = (now.replace(day=15) - timedelta(days=30 * month_offset))
        
        # Upward trend: +2% to +7% per month
        growth_factor = 1.0 + random.uniform(0.02, 0.07)
        base_revenue *= growth_factor
        
        num_invoices = random.randint(3, 8)
        
        for i in range(num_invoices):
            amount = (base_revenue / num_invoices) * random.uniform(0.8, 1.2)
            
            created_at = date + timedelta(days=random.randint(-5, 5))
            due_date = created_at + timedelta(days=30)
            
            invoices.append({
                'id': str(uuid.uuid4()),
                'businessId': business_id,
                'clientId': client_id,
                'createdBy': None,
                'invoiceNumber': f"SEED-{created_at.year}{created_at.month:02d}-{i+1}",
                'status': 'PAID',
                'issueDate': created_at,
                'dueDate': due_date,
                'totalAmount': round(amount, 2),
                'taxAmount': round(amount * 0.19, 2),
                'pdfUrl': 'seed_data.pdf',
                'notes': 'Generated by AI seeding script to create a realistic cashflow history.',
                'reminderCount': 0,
                'createdAt': created_at,
                'updatedAt': created_at,
                'deletedAt': None
            })

    print(f"Generated {len(invoices)} historical invoices.")
    
    # Insert in batches
    insert_query = text("""
        INSERT INTO "Invoice" (
            id, "businessId", "clientId", "createdBy", "invoiceNumber", 
            status, "issueDate", "dueDate", "totalAmount", "taxAmount", 
            "pdfUrl", notes, "reminderCount", "createdAt", "updatedAt", "deletedAt"
        ) VALUES (
            :id, :businessId, :clientId, :createdBy, :invoiceNumber, 
            :status, :issueDate, :dueDate, :totalAmount, :taxAmount, 
            :pdfUrl, :notes, :reminderCount, :createdAt, :updatedAt, :deletedAt
        )
    """)
    
    inserted_count = 0
    with invoice_engine.begin() as conn:
        for invoice in invoices:
            conn.execute(insert_query, invoice)
            inserted_count += 1
            
    print(f"✅ Successfully seeded {inserted_count} realistic invoices into the database!")

if __name__ == "__main__":
    try:
        seed_invoices()
    except Exception as e:
        print(f"Error seeding database: {e}")
