import os
import uuid
import random
from datetime import datetime, timedelta
from sqlalchemy import text
from database import engine, invoice_engine

def seed_data_2024_2026():
    business_id = '6f0e41ce-df82-4a5b-b6f6-2706bec7dbc2'
    user_id = str(uuid.uuid4())
    
    # 1. Setup Client for invoices
    with invoice_engine.connect() as conn:
        result = conn.execute(text('SELECT "clientId" FROM "Invoice" WHERE "businessId" = :bid LIMIT 1'), {'bid': business_id}).fetchone()
        client_id = result[0] if result else str(uuid.uuid4())
    
    # 2. Setup Category for expenses
    with engine.connect() as conn:
        # Check if we can find a user
        try:
            res_user = conn.execute(text('SELECT id FROM "User" LIMIT 1')).fetchone()
            if res_user:
                user_id = str(res_user[0])
        except Exception:
            pass

        try:
            res_cat = conn.execute(text('SELECT id FROM "ExpenseCategory" WHERE "businessId" = :bid LIMIT 1'), {'bid': business_id}).fetchone()
            if res_cat:
                category_id = str(res_cat[0])
            else:
                category_id = str(uuid.uuid4())
                conn.execute(text("""
                    INSERT INTO "ExpenseCategory" (id, "businessId", name, description, "createdAt", "updatedAt")
                    VALUES (:id, :bid, 'Frais Généraux (Auto-Généré)', 'Dépenses courantes', NOW(), NOW())
                """), {'id': category_id, 'bid': business_id})
                conn.commit()
        except Exception as e:
            print(f"ExpenseCategory setup failed (maybe table missing): {e}")
            category_id = str(uuid.uuid4())

    print(f"Seeding 2024-2026 data for business {business_id}...")
    
    # Configuration for generation
    start_date = datetime(2024, 1, 1)
    end_date = datetime(2026, 12, 31)
    current_date = start_date
    
    invoices = []
    expenses = []
    
    base_revenue = 8000.0
    base_expense = 3000.0

    while current_date <= end_date:
        # Simulate slight monthly upward trend with random bumps
        growth_factor = 1.0 + random.uniform(0.01, 0.05)
        base_revenue *= growth_factor
        base_expense *= (growth_factor * random.uniform(0.9, 1.1)) # Expenses follow revenue loosely
        
        # Add some seasonality (higher in Q4, lower in summer)
        month = current_date.month
        seasonality = 1.0
        if month in [10, 11, 12]:
            seasonality = 1.3
        elif month in [7, 8]:
            seasonality = 0.8
            
        monthly_revenue = base_revenue * seasonality
        monthly_expense = base_expense * seasonality
        
        # 1. Generate Invoices for this month
        num_invoices = random.randint(4, 12)
        for i in range(num_invoices):
            amount = (monthly_revenue / num_invoices) * random.uniform(0.7, 1.3)
            
            # Random day in month
            day = random.randint(1, 28)
            created_at = current_date.replace(day=day)
            due_date = created_at + timedelta(days=30)
            
            # Some recent invoices might be DRAFT, SENT, or OVERDUE, older ones are PAID
            status = 'PAID'
            now = datetime.now()
            if created_at > now:
                status = 'DRAFT' if random.random() > 0.5 else 'SENT'
            elif (now - created_at).days < 30:
                status = random.choice(['SENT', 'PAID'])
            elif (now - created_at).days > 30 and (now - created_at).days < 60:
                status = 'OVERDUE' if random.random() > 0.7 else 'PAID'

            invoices.append({
                'id': str(uuid.uuid4()),
                'businessId': business_id,
                'clientId': client_id,
                'createdBy': None,
                'invoiceNumber': f"INV-{created_at.year}{created_at.month:02d}-{i+1}",
                'status': status,
                'issueDate': created_at,
                'dueDate': due_date,
                'totalAmount': round(amount, 2),
                'taxAmount': round(amount * 0.19, 2),
                'pdfUrl': 'auto_generated.pdf',
                'notes': 'Generated by AI seeding script (2024-2026).',
                'reminderCount': 0,
                'createdAt': created_at,
                'updatedAt': created_at,
                'deletedAt': None
            })
            
        # 2. Generate Expenses for this month
        num_expenses = random.randint(3, 10)
        for i in range(num_expenses):
            amount = (monthly_expense / num_expenses) * random.uniform(0.5, 1.5)
            
            day = random.randint(1, 28)
            expense_date = current_date.replace(day=day)
            
            expenses.append({
                'id': str(uuid.uuid4()),
                'businessId': business_id,
                'amount': round(amount, 2),
                'date': expense_date,
                'description': f"Dépense opérationnelle auto-générée ({expense_date.strftime('%B %Y')})",
                'receiptUrl': None,
                'status': 'APPROVED' if expense_date < datetime.now() else 'PENDING',
                'rejectionReason': None,
                'categoryId': category_id,
                'createdBy': user_id,
                'createdAt': expense_date,
                'updatedAt': expense_date,
                'deletedAt': None
            })

        # Move to next month
        if current_date.month == 12:
            current_date = current_date.replace(year=current_date.year + 1, month=1)
        else:
            current_date = current_date.replace(month=current_date.month + 1)


    print(f"Generated {len(invoices)} invoices and {len(expenses)} expenses.")

    # 3. Insert Invoices
    insert_inv_query = text("""
        INSERT INTO "Invoice" (
            id, "businessId", "clientId", "createdBy", "invoiceNumber", 
            status, "issueDate", "dueDate", "totalAmount", "taxAmount", 
            "pdfUrl", notes, "reminderCount", "createdAt", "updatedAt", "deletedAt"
        ) VALUES (
            :id, :businessId, :clientId, :createdBy, :invoiceNumber, 
            :status, :issueDate, :dueDate, :totalAmount, :taxAmount, 
            :pdfUrl, :notes, :reminderCount, :createdAt, :updatedAt, :deletedAt
        )
    """)
    
    with invoice_engine.begin() as conn:
        for inv in invoices:
            conn.execute(insert_inv_query, inv)
            
    print(f"✅ Inserted {len(invoices)} invoices.")

    # 4. Insert Expenses
    insert_exp_query = text("""
        INSERT INTO "Expense" (
            id, "businessId", amount, date, description, "receiptUrl", status, 
            "rejectionReason", "categoryId", "createdBy", "createdAt", "updatedAt", "deletedAt"
        ) VALUES (
            :id, :businessId, :amount, :date, :description, :receiptUrl, :status, 
            :rejectionReason, :categoryId, :createdBy, :createdAt, :updatedAt, :deletedAt
        )
    """)
    
    try:
        with engine.begin() as conn:
            for exp in expenses:
                conn.execute(insert_exp_query, exp)
        print(f"✅ Inserted {len(expenses)} expenses.")
    except Exception as e:
        print(f"⚠️ Failed to insert expenses (table might not exist in this DB): {e}")

    print("🎉 Full realistic 2024-2026 data seeding complete!")

if __name__ == "__main__":
    seed_data_2024_2026()
